### PR TITLE
Support windows. go fmt main.go.

### PR DESCRIPTION
**Pull request by kardianos**
Windows doesn't support MakeRaw.
Sorry about diff. Orig file wasn't gofmt'ed.

### CODE REVIEW

**Comment by alfredxing** [comment]
I was wary of that when using it, but after looking at the [source](https://github.com/golang/crypto/tree/master/ssh/terminal), I found that there was a `util_windows.go` file... do you know if that works?

**Comment by kardianos** [comment]
terminal.MakeRaw is in util.go. It should probably be in util_linux.go.
There isn't a really great windows equivalent. This pull request just
doesn't call it on windows.

**Comment by alfredxing** [comment]
`MakeRaw` is defined in `util_windows.go` as well, though: https://github.com/golang/crypto/blob/master/ssh/terminal/util_windows.go#L84, so I thought it would have used that instead of what's defined, especially because of the defined build constraints?

**Comment by kardianos** [comment]
You're correct, it is in util_windows. Something else might be going on.
I'll look at it later tonight probably.

**Comment by kardianos** [comment]
The issue in this case was that on widnows the Stdin file descriptor is not zero, unlike unix. Rather pull the Fd() from the Stdin file descriptor. Still do not MakeRaw on windows as it results in no input echo, which is different then Unix. I suspect the terminal package could use some love on windows. But for now, this works well.

**Comment by alfredxing** [comment]
Thanks for looking into this! What are the implications of not calling `MakeRaw`? Wouldn't that mean a lot of the terminal features would be unavailable?

**Comment by kardianos** [comment]
It works fine. At least on windows.

**Comment by alfredxing** [comment]
Interesting. I'll merge this in then!

**Comment by ReneHSZ** [comment]
It still doesn't work.
Error message:
`panic: The handle is invalid.`
`C:/Program Files (x86)/go/src/runtime/panic.go:464 +0x3f4`
`main.main()`
`C:/Users/H/Desktop/go/src/github.com/alfredxing/calc/main.go:37 +0x47d`

**Pull request merged**
